name: Build
on: [push, pull_request]
jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.16

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          pip install cython==0.29.33

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable
          command: buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}

      - name: Upload buildozer.log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: buildozer.log
          path: buildozer.log

      - name: Debug information
        if: failure()
        run: |
          echo "Buildozer version:"
          buildozer --version
          echo "Python version:"
          python --version
          echo "Pip list:"
          pip list
          echo "Contents of .buildozer directory:"
          ls -R .buildozer
          echo "Last 100 lines of buildozer.log:"
          tail -n 100 buildozer.log
