name: Build
on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.16

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0
          pip install cython==0.29.33
          pip install --upgrade virtualenv

      - name: Install Android build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libtool autoconf automake python3-pip python3-dev python3-virtualenv python3-setuptools
          sudo apt-get install -y libffi-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
          sudo apt-get install -y openjdk-11-jdk

      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: ${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Create .buildozer directory
        run: |
          mkdir -p .buildozer
          touch .buildozer/.gitkeep

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable
          command: buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}

      - name: List .buildozer contents
        if: always()
        run: |
          echo "Contents of .buildozer directory:"
          ls -R .buildozer

      - name: Upload buildozer.log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: buildozer.log
          path: .buildozer/buildozer.log

      - name: Debug information
        if: failure()
        run: |
          echo "Buildozer version:"
          buildozer --version
          echo "Python version:"
          python --version
          echo "Pip list:"
          pip list
          echo "Contents of .buildozer directory:"
          ls -R .buildozer
          echo "Last 200 lines of buildozer.log:"
          if [ -f .buildozer/buildozer.log ]; then
            tail -n 200 .buildozer/buildozer.log
          else
            echo "buildozer.log not found"
          fi
